### ISSUE TITLE
boost::interprocess fails in standard docker/podman containers

### ISSUE THREAD

**Issue by dsschult** [icecube/photospline#23] opened 2022-06-06 14:48 UTC
When running in docker/podman, boost::interprocess will crash with a strange error.  This has to do with how ipc namespaces are handled inside of a container, and the "easy but insecure" solution is to run with `--ipc=host`.  Note that this does not affect singularity, as it does not use a different ipc namespace.

This is not a huge problem yet, but I can foresee this becoming one if users try to run anything using photospline on their laptops.  This at least needs to be documented, and preferably it should work out of the box with the new ipc namespace generated in the container.

[example_run.txt](https://github.com/icecube/photospline/files/8845226/example_run.txt)
[example_script.py.txt](https://github.com/icecube/photospline/files/8845232/example_script.py.txt)
[gdb_bt.txt](https://github.com/icecube/photospline/files/8845234/gdb_bt.txt)

**Comment by briedel** [comment] 2023-01-05 21:35
I have been running into this issue when running the skymap scanner running in K8s. If there is a file in `/dev/shm` photospline will just sit there waiting forever. It would be better to die rather than wait forever.

**Comment by cnweaver** [comment] 2023-01-05 21:39
Can you be more specific about 'a file'? Any file? A file that represents a shared memory segment that it wants to use? It would also be useful to have a stack trace of which part or operation in the code is doing the waiting, in order to have some idea what check might be needed to detect the failure before getting stuck (if any is possible). It is also generally unclear whether any of these aspects are bugs or possible to handle in photospline, or whether this is all at the photonics service layer.

**Comment by briedel** [comment] 2023-01-06 18:07
I was able to solve part of this in K8s without `hostIPC: true` by creating a RAM drive that mounds to `/dev/shm`. The solution is explained in:
https://medium.com/dive-into-ml-ai/raising-shared-memory-limit-of-a-kubernetes-container-62aae0468a33

**Comment by briedel** [comment] 2023-01-06 18:09
> Can you be more specific about 'a file'? Any file? A file that represents a shared memory segment that it wants to use? It would also be useful to have a stack trace of which part or operation in the code is doing the waiting, in order to have some idea what check might be needed to detect the failure before getting stuck (if any is possible). It is also generally unclear whether any of these aspects are bugs or possible to handle in photospline, or whether this is all at the photonics service layer.

The file that is in `/dev/shm` is `I3Photospline*`, i.e. the shared memory segment.

**Comment by cnweaver** [comment] 2023-01-06 18:10
Between this and discussions on Slack, I think that this is primarily a photonics-service issue, not a photospline issue, although it's worth thinking about whether there are ways to refactor which might make it easier to solve the problem at that higher level.

**Comment by jvansanten** [comment] 2023-01-09 15:18
Closing in favour of https://github.com/icecube/icetray/issues/2995

**Comment by jvansanten** [comment] 2023-01-09 15:20
Closing in favor of https://github.com/icecube/icetray/issues/2995

**Closed by jvansanten** 2023-01-09 15:20 UTC
Labels: invalid

**Comment by briedel** [comment] 2023-01-09 15:56
> Between this and discussions on Slack, I think that this is primarily a photonics-service issue, not a photospline issue, although it's worth thinking about whether there are ways to refactor which might make it easier to solve the problem at that higher level.

I am somewhat confused. This infinite hang occurs in Docker/Podman/containerd (at least for me) when:
1. There is a shared memory segment already present (most likely mounted from the host) at startup of the icetray script
2. When the icetray script is called in a Python subprocess and exits - This is intermittent cause who doesn't love an intermittent error

I think the issue is that there is a lock on the file in one container and the other container can't tell if that lock has been released or not

Somewhat more context:

From docker docs by default:
```
If not specified, daemon default is used, which can either be "private" or "shareable", depending on the daemon version and configuration.
```
this means
```
“private” | Own private IPC namespace.
“shareable” | Own private IPC namespace, with a possibility to share it with other containers.
```

Looks like we are defaulting to `shareable`

For OpenMPI applications Docker suggests:

```
Shared memory segments are used to accelerate inter-process communication at memory speed, rather than through pipes or through the network stack. Shared memory is commonly used by databases and custom-built (typically C/OpenMPI, C++/using boost libraries) high performance applications for scientific computing and financial services industries. If these types of applications are broken into multiple containers, you might need to share the IPC mechanisms of the containers, using "shareable" mode for the main (i.e. “donor”) container, and "container:<donor-name-or-ID>" for other containers.
```

This seems complicated within k8s, but I am not a k8s guru/magician/necromancer. I will talk to the folks at Google about it.

**Comment by cnweaver** [comment] 2023-01-09 16:16
> I think the issue is that there is a lock on the file in one container and the other container can't tell if that lock has been released or not

Specifically, if the process which took the lock to construct the table object dies, the lock is _not_ released, but other processes cannot tell that the process which owns it is dead and will never release it. All logic governing how this is done in icetray is in photonics-service, however, photospline itself only constructs tables using an allocator given to it, in whatever memory that allocates. I am considering how we might restructure photospline's code to reduce the duration for which such a lock must be held, or make the construction operation resumable, but those it's not clear how easy those goals might be to achieve. (Resumption, in particular, may not be possible due to inherent ambiguity of whether another process is still alive and might continue trying to do the work as well.)
